// resources/js/pages/contacts/create.tsx
import { Head, useForm } from "@inertiajs/react";
import { Button } from "@/components/ui/button";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import {
    index as contactsIndex,
    store as contactsStore,
} from "@/routes/contacts";

interface Props {
    contactType: string;
}

const managerRoleOptions = [
    { value: "Admins", label: "Admin" },
    { value: "accountingManagers", label: "Accounting Manager" },
    { value: "serviceManagers", label: "Service Manager" },
    { value: "marketingManagers", label: "Marketing Manager" },
    { value: "salesAndLeasingManagers", label: "Sales & Leasing Manager" },
] as const;

export default function ContactCreate({ contactType }: Props) {
    const { data, setData, post, processing, errors } = useForm({
        contact_type: contactType,
        role: "",
        first_name: "",
        last_name: "",
        email: "",
        phone_number: "",
        national_phone_number: "",
        phone_country_code: "SA",
        gender: "",
        national_id: "",
        nationality: "",
        georgian_birthdate: "",
        active: true,
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        post(contactsStore.url());
    };

    return (
        <>
            <Head title="Create Contact" />

            <div className="flex h-full flex-1 flex-col gap-4 p-4">
                <div>
                    <h1 className="text-2xl font-bold">Create Contact</h1>
                    <p className="text-muted-foreground">
                        Add a new {data.contact_type}
                    </p>
                </div>

                <Card className="max-w-2xl">
                    <CardHeader>
                        <CardTitle>Contact Details</CardTitle>
                        <CardDescription>
                            Enter the contact information
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div className="space-y-2">
                                <Label htmlFor="contact_type">
                                    Contact Type
                                </Label>
                                <Select
                                    value={data.contact_type}
                                    onValueChange={(value) => {
                                        setData("contact_type", value);
                                        if (value !== "admin") {
                                            setData("role", "");
                                        }
                                    }}
                                >
                                    <SelectTrigger>
                                        <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="owner">
                                            Owner
                                        </SelectItem>
                                        <SelectItem value="tenant">
                                            Tenant
                                        </SelectItem>
                                        <SelectItem value="admin">
                                            Admin
                                        </SelectItem>
                                        <SelectItem value="professional">
                                            Professional
                                        </SelectItem>
                                    </SelectContent>
                                </Select>
                                {errors.contact_type && (
                                    <p className="text-destructive text-sm">
                                        {errors.contact_type}
                                    </p>
                                )}
                            </div>

                            {data.contact_type === "admin" && (
                                <div className="space-y-2">
                                    <Label htmlFor="role">Manager Role</Label>
                                    <Select
                                        value={data.role}
                                        onValueChange={(value) =>
                                            setData("role", value)
                                        }
                                    >
                                        <SelectTrigger id="role">
                                            <SelectValue placeholder="Select manager role" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {managerRoleOptions.map((option) => (
                                                <SelectItem
                                                    key={option.value}
                                                    value={option.value}
                                                >
                                                    {option.label}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                    {errors.role && (
                                        <p className="text-destructive text-sm">
                                            {errors.role}
                                        </p>
                                    )}
                                </div>
                            )}

                            <div className="grid gap-4 md:grid-cols-2">
                                <div className="space-y-2">
                                    <Label htmlFor="first_name">
                                        First Name
                                    </Label>
                                    <Input
                                        id="first_name"
                                        value={data.first_name}
                                        onChange={(e) =>
                                            setData(
                                                "first_name",
                                                e.target.value,
                                            )
                                        }
                                        placeholder="Enter first name"
                                    />
                                    {errors.first_name && (
                                        <p className="text-destructive text-sm">
                                            {errors.first_name}
                                        </p>
                                    )}
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="last_name">Last Name</Label>
                                    <Input
                                        id="last_name"
                                        value={data.last_name}
                                        onChange={(e) =>
                                            setData("last_name", e.target.value)
                                        }
                                        placeholder="Enter last name"
                                    />
                                    {errors.last_name && (
                                        <p className="text-destructive text-sm">
                                            {errors.last_name}
                                        </p>
                                    )}
                                </div>
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="email">Email</Label>
                                <Input
                                    id="email"
                                    type="email"
                                    value={data.email}
                                    onChange={(e) =>
                                        setData("email", e.target.value)
                                    }
                                    placeholder="Enter email address"
                                />
                                {errors.email && (
                                    <p className="text-destructive text-sm">
                                        {errors.email}
                                    </p>
                                )}
                            </div>

                            <div className="grid gap-4 md:grid-cols-2">
                                <div className="space-y-2">
                                    <Label htmlFor="phone_number">
                                        Phone Number (International)
                                    </Label>
                                    <Input
                                        id="phone_number"
                                        value={data.phone_number}
                                        onChange={(e) =>
                                            setData(
                                                "phone_number",
                                                e.target.value,
                                            )
                                        }
                                        placeholder="+966500000000"
                                    />
                                    {errors.phone_number && (
                                        <p className="text-destructive text-sm">
                                            {errors.phone_number}
                                        </p>
                                    )}
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="national_phone_number">
                                        Phone Number (Local)
                                    </Label>
                                    <Input
                                        id="national_phone_number"
                                        value={data.national_phone_number}
                                        onChange={(e) =>
                                            setData(
                                                "national_phone_number",
                                                e.target.value,
                                            )
                                        }
                                        placeholder="0500000000"
                                    />
                                    {errors.national_phone_number && (
                                        <p className="text-destructive text-sm">
                                            {errors.national_phone_number}
                                        </p>
                                    )}
                                </div>
                            </div>

                            <div className="flex gap-4">
                                <Button type="submit" disabled={processing}>
                                    {processing
                                        ? "Creating..."
                                        : "Create Contact"}
                                </Button>
                                <Button
                                    type="button"
                                    variant="outline"
                                    onClick={() => window.history.back()}
                                >
                                    Cancel
                                </Button>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </>
    );
}

ContactCreate.layout = {
    breadcrumbs: [
        { title: "Contacts", href: contactsIndex() },
        { title: "Create", href: "#" },
    ],
};

// resources/js/pages/contacts/admins/Create.vue
<script setup lang="ts">
import { Head, useForm } from '@inertiajs/vue3';
import Heading from '@/components/Heading.vue';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

defineOptions({ layout: { breadcrumbs: [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Admins', href: '/admins' }, { title: 'New Admin', href: '/admins/create' }] } });

const form = useForm({ first_name: '', last_name: '', email: '', phone_number: '', phone_country_code: 'SA', role: 'Admins', national_id: '', gender: '' });

function submit() { form.post('/admins'); }
</script>

<template>
    <Head title="New Admin" />
    <div class="flex flex-col gap-6 p-4">
        <Heading variant="small" title="Create Admin" description="Add a new administrator." />
        <form @submit.prevent="submit" class="max-w-2xl space-y-6">
            <div class="grid gap-4 sm:grid-cols-2">
                <div class="grid gap-2"><Label for="first_name">First Name</Label><Input id="first_name" v-model="form.first_name" required /><InputError :message="form.errors.first_name" /></div>
                <div class="grid gap-2"><Label for="last_name">Last Name</Label><Input id="last_name" v-model="form.last_name" required /><InputError :message="form.errors.last_name" /></div>
            </div>
            <div class="grid gap-2"><Label for="email">Email</Label><Input id="email" v-model="form.email" type="email" /><InputError :message="form.errors.email" /></div>
            <div class="grid gap-4 sm:grid-cols-2">
                <div class="grid gap-2"><Label for="phone_country_code">Country Code</Label><Input id="phone_country_code" v-model="form.phone_country_code" required maxlength="5" /><InputError :message="form.errors.phone_country_code" /></div>
                <div class="grid gap-2"><Label for="phone_number">Phone Number</Label><Input id="phone_number" v-model="form.phone_number" required /><InputError :message="form.errors.phone_number" /></div>
            </div>
            <div class="grid gap-4 sm:grid-cols-2">
                <div class="grid gap-2">
                    <Label for="role">Role</Label>
                    <Select v-model="form.role">
                        <SelectTrigger id="role" class="w-full">
                            <SelectValue placeholder="Select role" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="Admins">Admin</SelectItem>
                            <SelectItem value="accountingManagers">Accounting Manager</SelectItem>
                            <SelectItem value="serviceManagers">Service Manager</SelectItem>
                            <SelectItem value="marketingManagers">Marketing Manager</SelectItem>
                            <SelectItem value="salesAndLeasingManagers">Sales & Leasing Manager</SelectItem>
                        </SelectContent>
                    </Select>
                    <InputError :message="form.errors.role" />
                </div>
                <div class="grid gap-2">
                    <Label for="gender">Gender</Label>
                    <Select v-model="form.gender">
                        <SelectTrigger id="gender" class="w-full">
                            <SelectValue placeholder="Select gender" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="male">Male</SelectItem>
                            <SelectItem value="female">Female</SelectItem>
                        </SelectContent>
                    </Select>
                    <InputError :message="form.errors.gender" />
                </div>
            </div>
            <div class="grid gap-2"><Label for="national_id">National ID</Label><Input id="national_id" v-model="form.national_id" /><InputError :message="form.errors.national_id" /></div>
            <div class="flex items-center gap-4"><Button :disabled="form.processing">Create Admin</Button></div>
        </form>
    </div>
</template>
