// resources/js/pages/requests/Show.vue
<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { ServiceRequest } from '@/types';

const props = defineProps<{ serviceRequest: ServiceRequest }>();
defineOptions({ layout: { breadcrumbs: [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Requests', href: '/requests' }, { title: 'Details', href: '#' }] } });

function deleteRequest() { if (confirm('Are you sure?')) { router.delete(`/requests/${props.serviceRequest.id}`); } }
</script>

<template>
    <Head :title="`Request #${serviceRequest.id}`" />
    <div class="flex flex-col gap-6 p-4">
        <div class="flex items-center justify-between">
            <div>
                <h2 class="text-2xl font-bold tracking-tight">Request #{{ serviceRequest.id }}</h2>
                <p class="text-muted-foreground text-sm">{{ serviceRequest.category?.name }} &middot; {{ serviceRequest.subcategory?.name }}</p>
            </div>
            <div class="flex items-center gap-2">
                <Button variant="outline" as-child><Link :href="`/requests/${serviceRequest.id}/edit`">Edit</Link></Button>
                <Button variant="destructive" @click="deleteRequest">Delete</Button>
            </div>
        </div>

        <div class="grid gap-4 md:grid-cols-3">
            <Card><CardHeader class="pb-2"><CardTitle class="text-sm font-medium">Status</CardTitle></CardHeader><CardContent><Badge>{{ serviceRequest.status?.name ?? '—' }}</Badge></CardContent></Card>
            <Card><CardHeader class="pb-2"><CardTitle class="text-sm font-medium">Priority</CardTitle></CardHeader><CardContent><Badge variant="secondary">{{ serviceRequest.priority ?? '—' }}</Badge></CardContent></Card>
            <Card><CardHeader class="pb-2"><CardTitle class="text-sm font-medium">Created</CardTitle></CardHeader><CardContent><span>{{ serviceRequest.created_at }}</span></CardContent></Card>
        </div>

        <div class="grid gap-4 md:grid-cols-2">
            <Card>
                <CardHeader><CardTitle>Location</CardTitle></CardHeader>
                <CardContent class="space-y-2">
                    <div class="flex justify-between"><span class="text-muted-foreground">Community</span><span>{{ serviceRequest.community?.name ?? '—' }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Unit</span><span>{{ serviceRequest.unit?.name ?? '—' }}</span></div>
                </CardContent>
            </Card>
            <Card>
                <CardHeader><CardTitle>People</CardTitle></CardHeader>
                <CardContent class="space-y-2">
                    <div class="flex justify-between"><span class="text-muted-foreground">Requester</span><span>{{ (serviceRequest as any).requester?.first_name }} {{ (serviceRequest as any).requester?.last_name }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Assignee</span><span>{{ (serviceRequest as any).assignee ? `${(serviceRequest as any).assignee.first_name} ${(serviceRequest as any).assignee.last_name}` : '—' }}</span></div>
                </CardContent>
            </Card>
        </div>

        <Card v-if="serviceRequest.description">
            <CardHeader><CardTitle>Description</CardTitle></CardHeader>
            <CardContent><p class="whitespace-pre-wrap">{{ serviceRequest.description }}</p></CardContent>
        </Card>
    </div>
</template>

// resources/js/pages/service-requests/show.tsx
import { Head, Link } from '@inertiajs/react';
import AppLayout from '@/layouts/app-layout';
import { Button } from '@/components/ui/button';
import { edit } from '@/routes/service-requests';

interface Props {
    request: any;
}

export default function Show({ request }: Props) {
    return (
        <AppLayout>
            <Head title={`Request #${request.request_number}`} />

            <div className="space-y-6">
                <div className="flex items-center justify-between">
                    <div>
                        <h1 className="text-3xl font-bold">{request.title}</h1>
                        <p className="text-muted-foreground">Request #{request.request_number}</p>
                    </div>
                    <Link href={edit(request.id)}>
                        <Button variant="outline">Edit</Button>
                    </Link>
                </div>

                <div className="grid gap-6">
                    <div className="rounded-lg border bg-card p-6">
                        <h2 className="text-lg font-semibold mb-4">Request Details</h2>
                        <dl className="grid grid-cols-2 gap-4">
                            <div>
                                <dt className="text-sm font-medium text-muted-foreground">Status</dt>
                                <dd className="mt-1">{request.status.name}</dd>
                            </div>
                            <div>
                                <dt className="text-sm font-medium text-muted-foreground">Priority</dt>
                                <dd className="mt-1 capitalize">{request.priority}</dd>
                            </div>
                            <div className="col-span-2">
                                <dt className="text-sm font-medium text-muted-foreground">Description</dt>
                                <dd className="mt-1">{request.description || 'No description provided'}</dd>
                            </div>
                        </dl>
                    </div>

                    {/* TODO: Add more detail sections for history, attachments, etc. */}
                </div>
            </div>
        </AppLayout>
    );
}
