// resources/js/components/app-sidebar.tsx
import { Link } from "@inertiajs/react";
import {
    BookOpen,
    Building2,
    FileText,
    FolderGit2,
    Home,
    LayoutGrid,
    MapPin,
    Users,
    Wrench,
} from "lucide-react";
import AppLogo from "@/components/app-logo";
import { NavFooter } from "@/components/nav-footer";
import { NavMain } from "@/components/nav-main";
import { NavUser } from "@/components/nav-user";
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from "@/components/ui/sidebar";
import { dashboard } from "@/routes";
import { index as buildingsIndex } from "@/routes/buildings";
import { index as communitiesIndex } from "@/routes/communities";
import { index as contactsIndex } from "@/routes/contacts";
import { index as serviceRequestsIndex } from "@/routes/service-requests";
import { index as unitsIndex } from "@/routes/units";
import type { NavItem } from "@/types";

const mainNavItems: NavItem[] = [
    {
        title: "Dashboard",
        href: dashboard(),
        icon: LayoutGrid,
    },
    {
        title: "Communities",
        href: communitiesIndex(),
        icon: MapPin,
    },
    {
        title: "Buildings",
        href: buildingsIndex(),
        icon: Building2,
    },
    {
        title: "Units",
        href: unitsIndex(),
        icon: Home,
    },
    {
        title: "Contacts",
        href: contactsIndex(),
        icon: Users,
    },
    {
        title: "Service Requests",
        href: serviceRequestsIndex(),
        icon: Wrench,
    },
    {
        title: "Leasing",
        href: "/leasing",
        icon: FileText,
    },
];

const footerNavItems: NavItem[] = [
    {
        title: "Repository",
        href: "https://github.com/laravel/react-starter-kit",
        icon: FolderGit2,
    },
    {
        title: "Documentation",
        href: "https://laravel.com/docs/starter-kits#react",
        icon: BookOpen,
    },
];

export function AppSidebar() {
    return (
        <Sidebar collapsible="icon" variant="inset">
            <SidebarHeader>
                <SidebarMenu>
                    <SidebarMenuItem>
                        <SidebarMenuButton size="lg" asChild>
                            <Link href={dashboard()} prefetch>
                                <AppLogo />
                            </Link>
                        </SidebarMenuButton>
                    </SidebarMenuItem>
                </SidebarMenu>
            </SidebarHeader>

            <SidebarContent>
                <NavMain items={mainNavItems} />
            </SidebarContent>

            <SidebarFooter>
                <NavFooter items={footerNavItems} className="mt-auto" />
                <NavUser />
            </SidebarFooter>
        </Sidebar>
    );
}

// resources/js/components/AppSidebar.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3';
import {
    Building2,
    CalendarCheck,
    ClipboardList,
    DoorOpen,
    FileText,
    LayoutGrid,
    Megaphone,
    Receipt,
    Users,
} from 'lucide-vue-next';
import AppLogo from '@/components/AppLogo.vue';
import NavGroups from '@/components/NavGroups.vue';
import NavMain from '@/components/NavMain.vue';
import NavUser from '@/components/NavUser.vue';
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from '@/components/ui/sidebar';
import { dashboard } from '@/routes';
import type { NavGroup, NavItem } from '@/types';

const mainNavItems: NavItem[] = [
    {
        title: 'Dashboard',
        href: dashboard(),
        icon: LayoutGrid,
    },
];

const navGroups: NavGroup[] = [
    {
        title: 'Properties',
        icon: Building2,
        items: [
            { title: 'Communities', href: '/communities' },
            { title: 'Buildings', href: '/buildings' },
            { title: 'Units', href: '/units' },
        ],
    },
    {
        title: 'Leasing',
        icon: FileText,
        items: [
            { title: 'Leases', href: '/leases' },
        ],
    },
    {
        title: 'Requests',
        icon: ClipboardList,
        items: [
            { title: 'All Requests', href: '/requests' },
        ],
    },
    {
        title: 'Facilities',
        icon: CalendarCheck,
        items: [
            { title: 'Facilities', href: '/facilities' },
            { title: 'Bookings', href: '/facility-bookings' },
        ],
    },
    {
        title: 'Accounting',
        icon: Receipt,
        items: [
            { title: 'Transactions', href: '/transactions' },
        ],
    },
    {
        title: 'Communication',
        icon: Megaphone,
        items: [
            { title: 'Announcements', href: '/announcements' },
        ],
    },
    {
        title: 'Contacts',
        icon: Users,
        items: [
            { title: 'Owners', href: '/owners' },
            { title: 'Tenants', href: '/residents' },
            { title: 'Admins', href: '/admins' },
            { title: 'Professionals', href: '/professionals' },
        ],
    },
    {
        title: 'Visitor Access',
        icon: DoorOpen,
        items: [
            { title: 'Visitor Access', href: '/requests?category=visitor-access' },
        ],
    },
];
</script>

<template>
    <Sidebar collapsible="icon" variant="inset">
        <SidebarHeader>
            <SidebarMenu>
                <SidebarMenuItem>
                    <SidebarMenuButton size="lg" as-child>
                        <Link :href="dashboard()">
                            <AppLogo />
                        </Link>
                    </SidebarMenuButton>
                </SidebarMenuItem>
            </SidebarMenu>
        </SidebarHeader>

        <SidebarContent>
            <NavMain :items="mainNavItems" />
            <NavGroups label="Modules" :items="navGroups" />
        </SidebarContent>

        <SidebarFooter>
            <NavUser />
        </SidebarFooter>
    </Sidebar>
    <slot />
</template>
