// resources/js/pages/facilities/Create.vue
<script setup lang="ts">
import { Head, useForm } from '@inertiajs/vue3';
import Heading from '@/components/Heading.vue';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import type { FacilityCategory } from '@/types';

defineOptions({ layout: { breadcrumbs: [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Facilities', href: '/facilities' }, { title: 'New Facility', href: '/facilities/create' }] } });

defineProps<{ categories: FacilityCategory[] }>();

const form = useForm({ name: '', category_id: '', community_id: '', capacity: '' });

function submit() { form.post('/facilities'); }
</script>

<template>
    <Head title="New Facility" />
    <div class="flex flex-col gap-6 p-4">
        <Heading variant="small" title="Create Facility" description="Add a new shared facility." />
        <form @submit.prevent="submit" class="max-w-2xl space-y-6">
            <div class="grid gap-2"><Label for="name">Facility Name</Label><Input id="name" v-model="form.name" required placeholder="e.g. Swimming Pool" /><InputError :message="form.errors.name" /></div>
            <div class="grid gap-4 sm:grid-cols-2">
                <div class="grid gap-2">
                    <Label for="category_id">Category</Label>
                    <select id="category_id" v-model="form.category_id" required class="border-input bg-background ring-offset-background flex h-10 w-full rounded-md border px-3 py-2 text-sm focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none">
                        <option value="" disabled>Select category</option>
                        <option v-for="cat in categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option>
                    </select>
                    <InputError :message="form.errors.category_id" />
                </div>
                <div class="grid gap-2"><Label for="community_id">Community ID</Label><Input id="community_id" v-model="form.community_id" type="number" required /><InputError :message="form.errors.community_id" /></div>
            </div>
            <div class="grid gap-2"><Label for="capacity">Capacity</Label><Input id="capacity" v-model="form.capacity" type="number" min="1" placeholder="Maximum occupancy" /><InputError :message="form.errors.capacity" /></div>
            <div class="flex items-center gap-4"><Button :disabled="form.processing">Create Facility</Button></div>
        </form>
    </div>
</template>

// resources/js/pages/properties/communities/create.tsx
import { Head, useForm } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { index as communitiesIndex, store as communitiesStore } from '@/routes/communities';

export default function CommunityCreate() {
    const { data, setData, post, processing, errors } = useForm({
        name: '',
        description: '',
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        post(communitiesStore());
    };

    return (
        <>
            <Head title="Create Community" />

            <div className="flex h-full flex-1 flex-col gap-4 p-4">
                <div>
                    <h1 className="text-2xl font-bold">Create Community</h1>
                    <p className="text-muted-foreground">Add a new community to your properties</p>
                </div>

                <Card className="max-w-2xl">
                    <CardHeader>
                        <CardTitle>Community Details</CardTitle>
                        <CardDescription>Enter the basic information for the new community</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div className="space-y-2">
                                <Label htmlFor="name">Name</Label>
                                <Input
                                    id="name"
                                    value={data.name}
                                    onChange={(e) => setData('name', e.target.value)}
                                    placeholder="Enter community name"
                                />
                                {errors.name && (
                                    <p className="text-destructive text-sm">{errors.name}</p>
                                )}
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="description">Description</Label>
                                <textarea
                                    id="description"
                                    value={data.description}
                                    onChange={(e) => setData('description', e.target.value)}
                                    placeholder="Enter community description (optional)"
                                    className="border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex min-h-24 w-full rounded-md border px-3 py-2 text-sm focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50"
                                />
                                {errors.description && (
                                    <p className="text-destructive text-sm">{errors.description}</p>
                                )}
                            </div>

                            <div className="flex gap-4">
                                <Button type="submit" disabled={processing}>
                                    {processing ? 'Creating...' : 'Create Community'}
                                </Button>
                                <Button type="button" variant="outline" onClick={() => window.history.back()}>
                                    Cancel
                                </Button>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </>
    );
}

CommunityCreate.layout = {
    breadcrumbs: [
        { title: 'Properties', href: communitiesIndex() },
        { title: 'Communities', href: communitiesIndex() },
        { title: 'Create', href: '#' },
    ],
};
