// resources/js/pages/requests/Edit.vue
<script setup lang="ts">
import { Head, useForm } from '@inertiajs/vue3';
import Heading from '@/components/Heading.vue';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import type { ServiceRequest } from '@/types';

const props = defineProps<{ serviceRequest: ServiceRequest }>();
defineOptions({ layout: { breadcrumbs: [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Requests', href: '/requests' }, { title: 'Edit', href: '#' }] } });

const form = useForm({
    category_id: props.serviceRequest.category_id ?? '',
    subcategory_id: props.serviceRequest.subcategory_id ?? '',
    unit_id: props.serviceRequest.unit_id ?? '',
    community_id: props.serviceRequest.community_id ?? '',
    description: props.serviceRequest.description ?? '',
    priority: props.serviceRequest.priority?.name ?? 'medium',
});

function submit() { form.put(`/requests/${props.serviceRequest.id}`); }
</script>

<template>
    <Head title="Edit Request" />
    <div class="flex flex-col gap-6 p-4">
        <Heading variant="small" title="Edit Request" description="Update the service request details." />
        <form @submit.prevent="submit" class="max-w-2xl space-y-6">
            <div class="grid gap-4 sm:grid-cols-2">
                <div class="grid gap-2"><Label for="category_id">Category</Label><Input id="category_id" v-model="form.category_id" type="number" required placeholder="Category ID" /><InputError :message="form.errors.category_id" /></div>
                <div class="grid gap-2"><Label for="subcategory_id">Subcategory</Label><Input id="subcategory_id" v-model="form.subcategory_id" type="number" placeholder="Subcategory ID" /><InputError :message="form.errors.subcategory_id" /></div>
            </div>
            <div class="grid gap-4 sm:grid-cols-2">
                <div class="grid gap-2"><Label for="community_id">Community</Label><Input id="community_id" v-model="form.community_id" type="number" placeholder="Community ID" /><InputError :message="form.errors.community_id" /></div>
                <div class="grid gap-2"><Label for="unit_id">Unit</Label><Input id="unit_id" v-model="form.unit_id" type="number" placeholder="Unit ID" /><InputError :message="form.errors.unit_id" /></div>
            </div>
            <div class="grid gap-2">
                <Label for="priority">Priority</Label>
                <select id="priority" v-model="form.priority" class="border-input bg-background ring-offset-background flex h-10 w-full rounded-md border px-3 py-2 text-sm focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none">
                    <option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option>
                </select>
                <InputError :message="form.errors.priority" />
            </div>
            <div class="grid gap-2"><Label for="description">Description</Label><Textarea id="description" v-model="form.description" placeholder="Describe the request..." /><InputError :message="form.errors.description" /></div>
            <div class="flex items-center gap-4"><Button :disabled="form.processing">Update Request</Button></div>
        </form>
    </div>
</template>

// resources/js/pages/properties/communities/edit.tsx
import { Head, useForm } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { index as communitiesIndex, update as communitiesUpdate } from '@/routes/communities';

interface Community {
    id: number;
    name: string;
    description?: string;
    status: 'active' | 'inactive';
}

interface Props {
    community: Community;
}

export default function CommunityEdit({ community }: Props) {
    const { data, setData, put, processing, errors } = useForm({
        name: community.name,
        description: community.description ?? '',
        status: community.status,
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        put(communitiesUpdate({ community: community.id }));
    };

    return (
        <>
            <Head title={`Edit ${community.name}`} />

            <div className="flex h-full flex-1 flex-col gap-4 p-4">
                <div>
                    <h1 className="text-2xl font-bold">Edit Community</h1>
                    <p className="text-muted-foreground">Update community details</p>
                </div>

                <Card className="max-w-2xl">
                    <CardHeader>
                        <CardTitle>Community Details</CardTitle>
                        <CardDescription>Modify the community information</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div className="space-y-2">
                                <Label htmlFor="name">Name</Label>
                                <Input
                                    id="name"
                                    value={data.name}
                                    onChange={(e) => setData('name', e.target.value)}
                                    placeholder="Enter community name"
                                />
                                {errors.name && (
                                    <p className="text-destructive text-sm">{errors.name}</p>
                                )}
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="description">Description</Label>
                                <textarea
                                    id="description"
                                    value={data.description}
                                    onChange={(e) => setData('description', e.target.value)}
                                    placeholder="Enter community description (optional)"
                                    className="border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex min-h-24 w-full rounded-md border px-3 py-2 text-sm focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50"
                                />
                                {errors.description && (
                                    <p className="text-destructive text-sm">{errors.description}</p>
                                )}
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="status">Status</Label>
                                <Select value={data.status} onValueChange={(value: 'active' | 'inactive') => setData('status', value)}>
                                    <SelectTrigger>
                                        <SelectValue placeholder="Select status" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="active">Active</SelectItem>
                                        <SelectItem value="inactive">Inactive</SelectItem>
                                    </SelectContent>
                                </Select>
                                {errors.status && (
                                    <p className="text-destructive text-sm">{errors.status}</p>
                                )}
                            </div>

                            <div className="flex gap-4">
                                <Button type="submit" disabled={processing}>
                                    {processing ? 'Saving...' : 'Save Changes'}
                                </Button>
                                <Button type="button" variant="outline" onClick={() => window.history.back()}>
                                    Cancel
                                </Button>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </>
    );
}

CommunityEdit.layout = {
    breadcrumbs: [
        { title: 'Properties', href: communitiesIndex() },
        { title: 'Communities', href: communitiesIndex() },
        { title: 'Edit', href: '#' },
    ],
};
