// resources/js/pages/properties/communities/show.tsx
import { Head, Link, router } from "@inertiajs/react";
import { Building2, Edit, MapPin, Plus, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog";
import {
    create as buildingsCreate,
    show as buildingsShow,
} from "@/routes/buildings";
import {
    index as communitiesIndex,
    edit as communitiesEdit,
    destroy as communitiesDestroy,
} from "@/routes/communities";

interface Building {
    id: number;
    name: string;
    status: string;
    no_floors: number;
    units_count: number;
}

interface Community {
    id: number;
    name: string;
    status: "active" | "inactive";
    description?: string;
    city?: { id: number; name: string };
    district?: { id: number; name: string };
    map?: { latitude: number; longitude: number };
    buildings: Building[];
    created_at: string;
    updated_at: string;
}

interface Props {
    community: Community;
}

export default function CommunityShow({ community }: Props) {
    const handleDelete = () => {
        router.delete(communitiesDestroy({ community: community.id }));
    };

    return (
        <>
            <Head title={community.name} />

            <div className="flex h-full flex-1 flex-col gap-4 p-4">
                {/* Header */}
                <div className="flex items-center justify-between">
                    <div>
                        <h1 className="text-2xl font-bold">{community.name}</h1>
                        <div className="text-muted-foreground flex items-center gap-2">
                            <MapPin className="h-4 w-4" />
                            {community.city?.name ?? "No city"},{" "}
                            {community.district?.name ?? "No district"}
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <Button variant="outline" asChild>
                            <Link
                                href={communitiesEdit({
                                    community: community.id,
                                })}
                            >
                                <Edit className="mr-2 h-4 w-4" />
                                Edit
                            </Link>
                        </Button>
                        <Dialog>
                            <DialogTrigger asChild>
                                <Button variant="destructive">
                                    <Trash2 className="mr-2 h-4 w-4" />
                                    Delete
                                </Button>
                            </DialogTrigger>
                            <DialogContent>
                                <DialogHeader>
                                    <DialogTitle>Delete Community</DialogTitle>
                                    <DialogDescription>
                                        Are you sure you want to delete this
                                        community? This action cannot be undone.
                                    </DialogDescription>
                                </DialogHeader>
                                <DialogFooter>
                                    <Button variant="outline">Cancel</Button>
                                    <Button
                                        variant="destructive"
                                        onClick={handleDelete}
                                    >
                                        Delete
                                    </Button>
                                </DialogFooter>
                            </DialogContent>
                        </Dialog>
                    </div>
                </div>

                {/* Overview Cards */}
                <div className="grid gap-4 md:grid-cols-3">
                    <Card>
                        <CardHeader className="pb-2">
                            <CardDescription>Status</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <Badge
                                variant={
                                    community.status === "active"
                                        ? "default"
                                        : "secondary"
                                }
                            >
                                {community.status}
                            </Badge>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader className="pb-2">
                            <CardDescription>Buildings</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">
                                {community.buildings.length}
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader className="pb-2">
                            <CardDescription>Total Units</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">
                                {community.buildings.reduce(
                                    (acc, b) => acc + b.units_count,
                                    0,
                                )}
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Description */}
                {community.description && (
                    <Card>
                        <CardHeader>
                            <CardTitle>Description</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <p className="text-muted-foreground">
                                {community.description}
                            </p>
                        </CardContent>
                    </Card>
                )}

                {/* Buildings */}
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between">
                        <div>
                            <CardTitle>Buildings</CardTitle>
                            <CardDescription>
                                Buildings in this community
                            </CardDescription>
                        </div>
                        <Button asChild>
                            <Link
                                href={
                                    buildingsCreate() +
                                    `?community_id=${community.id}`
                                }
                            >
                                <Plus className="mr-2 h-4 w-4" />
                                Add Building
                            </Link>
                        </Button>
                    </CardHeader>
                    <CardContent>
                        {community.buildings.length === 0 ? (
                            <div className="text-muted-foreground py-8 text-center">
                                No buildings yet. Add your first building to
                                this community.
                            </div>
                        ) : (
                            <div className="divide-y">
                                {community.buildings.map((building) => (
                                    <Link
                                        key={building.id}
                                        href={buildingsShow({
                                            building: building.id,
                                        })}
                                        className="hover:bg-muted/50 flex items-center justify-between p-4 transition-colors"
                                    >
                                        <div className="flex items-center gap-4">
                                            <div className="bg-primary/10 flex h-10 w-10 items-center justify-center rounded-lg">
                                                <Building2 className="text-primary h-5 w-5" />
                                            </div>
                                            <div>
                                                <div className="font-medium">
                                                    {building.name}
                                                </div>
                                                <div className="text-muted-foreground text-sm">
                                                    {building.no_floors} floors
                                                </div>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-4">
                                            <div className="text-muted-foreground text-sm">
                                                {building.units_count} units
                                            </div>
                                            <Badge
                                                variant={
                                                    building.status === "active"
                                                        ? "default"
                                                        : "secondary"
                                                }
                                            >
                                                {building.status}
                                            </Badge>
                                        </div>
                                    </Link>
                                ))}
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </>
    );
}

CommunityShow.layout = {
    breadcrumbs: [
        { title: "Properties", href: communitiesIndex() },
        { title: "Communities", href: communitiesIndex() },
    ],
};

// resources/js/pages/properties/communities/Show.vue
<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { Community } from '@/types';

const props = defineProps<{ community: Community }>();

defineOptions({
    layout: {
        breadcrumbs: [
            { title: 'Dashboard', href: '/dashboard' },
            { title: 'Communities', href: '/communities' },
            { title: 'Details', href: '#' },
        ],
    },
});

function deleteCommunity() {
    if (confirm('Are you sure you want to delete this community?')) {
        router.delete(`/communities/${props.community.id}`);
    }
}
</script>

<template>
    <Head :title="community.name" />

    <div class="flex flex-col gap-6 p-4">
        <div class="flex items-center justify-between">
            <div>
                <h2 class="text-2xl font-bold tracking-tight">{{ community.name }}</h2>
                <p class="text-muted-foreground text-sm">Community details and statistics</p>
            </div>
            <div class="flex items-center gap-2">
                <Button variant="outline" as-child>
                    <Link :href="`/communities/${community.id}/edit`">Edit</Link>
                </Button>
                <Button variant="destructive" @click="deleteCommunity">Delete</Button>
            </div>
        </div>

        <div class="grid gap-4 md:grid-cols-3">
            <Card>
                <CardHeader class="pb-2"><CardTitle class="text-sm font-medium">Buildings</CardTitle></CardHeader>
                <CardContent><div class="text-2xl font-bold">{{ community.buildings_count ?? 0 }}</div></CardContent>
            </Card>
            <Card>
                <CardHeader class="pb-2"><CardTitle class="text-sm font-medium">Units</CardTitle></CardHeader>
                <CardContent><div class="text-2xl font-bold">{{ community.units_count ?? 0 }}</div></CardContent>
            </Card>
            <Card>
                <CardHeader class="pb-2"><CardTitle class="text-sm font-medium">Requests</CardTitle></CardHeader>
                <CardContent><div class="text-2xl font-bold">{{ community.requests_count ?? 0 }}</div></CardContent>
            </Card>
        </div>

        <div class="grid gap-4 md:grid-cols-2">
            <Card>
                <CardHeader><CardTitle>Location</CardTitle></CardHeader>
                <CardContent class="space-y-2">
                    <div class="flex justify-between"><span class="text-muted-foreground">Country</span><span>{{ community.country?.name ?? '—' }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">City</span><span>{{ community.city?.name ?? '—' }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">District</span><span>{{ community.district?.name ?? '—' }}</span></div>
                </CardContent>
            </Card>
            <Card>
                <CardHeader><CardTitle>Financials</CardTitle></CardHeader>
                <CardContent class="space-y-2">
                    <div class="flex justify-between"><span class="text-muted-foreground">Currency</span><span>{{ community.currency?.name ?? '—' }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Sales Commission</span><span>{{ community.sales_commission_rate ?? '—' }}%</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Rental Commission</span><span>{{ community.rental_commission_rate ?? '—' }}%</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Marketplace</span><Badge :variant="community.is_market_place ? 'default' : 'secondary'">{{ community.is_market_place ? 'Yes' : 'No' }}</Badge></div>
                </CardContent>
            </Card>
        </div>

        <Card v-if="community.buildings && community.buildings.length > 0">
            <CardHeader><CardTitle>Buildings</CardTitle></CardHeader>
            <CardContent>
                <div class="space-y-2">
                    <Link v-for="building in community.buildings" :key="building.id" :href="`/buildings/${building.id}`" class="flex items-center justify-between rounded-md border p-3 hover:bg-muted/50">
                        <span class="font-medium">{{ building.name }}</span>
                        <span class="text-muted-foreground text-sm">{{ building.units_count ?? 0 }} units</span>
                    </Link>
                </div>
            </CardContent>
        </Card>

        <Card v-if="community.facilities && community.facilities.length > 0">
            <CardHeader><CardTitle>Facilities</CardTitle></CardHeader>
            <CardContent>
                <div class="space-y-2">
                    <Link v-for="facility in community.facilities" :key="facility.id" :href="`/facilities/${facility.id}`" class="flex items-center justify-between rounded-md border p-3 hover:bg-muted/50">
                        <span class="font-medium">{{ facility.name }}</span>
                        <Badge :variant="facility.is_active ? 'default' : 'secondary'">{{ facility.is_active ? 'Active' : 'Inactive' }}</Badge>
                    </Link>
                </div>
            </CardContent>
        </Card>
    </div>
</template>
