// resources/js/pages/contacts/show.tsx
import { Head, Link, router } from "@inertiajs/react";
import { Edit, Mail, Phone, Trash2, User } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog";
import {
    index as contactsIndex,
    edit as contactsEdit,
    destroy as contactsDestroy,
} from "@/routes/contacts";

interface Contact {
    id: number;
    contact_type: string;
    first_name: string;
    last_name: string;
    name: string;
    email: string;
    phone_number: string;
    national_phone_number: string;
    national_id?: string;
    gender?: string;
    active: boolean;
    created_at: string;
}

interface Props {
    contact: Contact;
}

export default function ContactShow({ contact }: Props) {
    const handleDelete = () => {
        router.delete(contactsDestroy({ contact: contact.id }));
    };

    const getContactTypeLabel = (type: string) => {
        return type.charAt(0).toUpperCase() + type.slice(1);
    };

    return (
        <>
            <Head title={contact.name} />

            <div className="flex h-full flex-1 flex-col gap-4 p-4">
                {/* Header */}
                <div className="flex items-center justify-between">
                    <div>
                        <h1 className="text-2xl font-bold">{contact.name}</h1>
                        <div className="text-muted-foreground flex items-center gap-2">
                            <User className="h-4 w-4" />
                            {getContactTypeLabel(contact.contact_type)}
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <Button variant="outline" asChild>
                            <Link href={contactsEdit({ contact: contact.id })}>
                                <Edit className="mr-2 h-4 w-4" />
                                Edit
                            </Link>
                        </Button>
                        <Dialog>
                            <DialogTrigger asChild>
                                <Button variant="destructive">
                                    <Trash2 className="mr-2 h-4 w-4" />
                                    Delete
                                </Button>
                            </DialogTrigger>
                            <DialogContent>
                                <DialogHeader>
                                    <DialogTitle>Delete Contact</DialogTitle>
                                    <DialogDescription>
                                        Are you sure you want to delete this
                                        contact? This action cannot be undone.
                                    </DialogDescription>
                                </DialogHeader>
                                <DialogFooter>
                                    <Button variant="outline">Cancel</Button>
                                    <Button
                                        variant="destructive"
                                        onClick={handleDelete}
                                    >
                                        Delete
                                    </Button>
                                </DialogFooter>
                            </DialogContent>
                        </Dialog>
                    </div>
                </div>

                {/* Overview Cards */}
                <div className="grid gap-4 md:grid-cols-3">
                    <Card>
                        <CardHeader className="pb-2">
                            <CardDescription>Status</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <Badge
                                variant={
                                    contact.active ? "default" : "secondary"
                                }
                            >
                                {contact.active ? "Active" : "Inactive"}
                            </Badge>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader className="pb-2">
                            <CardDescription>Contact Type</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">
                                {getContactTypeLabel(contact.contact_type)}
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader className="pb-2">
                            <CardDescription>Created</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="text-sm">
                                {new Date(
                                    contact.created_at,
                                ).toLocaleDateString()}
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Contact Information */}
                <Card>
                    <CardHeader>
                        <CardTitle>Contact Information</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="flex items-center gap-3">
                            <Mail className="text-muted-foreground h-5 w-5" />
                            <div>
                                <div className="text-muted-foreground text-sm">
                                    Email
                                </div>
                                <div>{contact.email}</div>
                            </div>
                        </div>
                        <div className="flex items-center gap-3">
                            <Phone className="text-muted-foreground h-5 w-5" />
                            <div>
                                <div className="text-muted-foreground text-sm">
                                    Phone
                                </div>
                                <div>{contact.phone_number}</div>
                            </div>
                        </div>
                        {contact.national_id && (
                            <div className="flex items-center gap-3">
                                <User className="text-muted-foreground h-5 w-5" />
                                <div>
                                    <div className="text-muted-foreground text-sm">
                                        National ID
                                    </div>
                                    <div>{contact.national_id}</div>
                                </div>
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </>
    );
}

ContactShow.layout = {
    breadcrumbs: [{ title: "Contacts", href: contactsIndex() }],
};

// resources/js/pages/contacts/residents/Show.vue
<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { Resident } from '@/types';

const props = defineProps<{ resident: Resident }>();
defineOptions({ layout: { breadcrumbs: [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Residents', href: '/residents' }, { title: 'Details', href: '#' }] } });

function deleteResident() { if (confirm('Are you sure?')) { router.delete(`/residents/${props.resident.id}`); } }
</script>

<template>
    <Head :title="`${resident.first_name} ${resident.last_name}`" />
    <div class="flex flex-col gap-6 p-4">
        <div class="flex items-center justify-between">
            <div>
                <h2 class="text-2xl font-bold tracking-tight">{{ resident.first_name }} {{ resident.last_name }}</h2>
                <Badge :variant="resident.active ? 'default' : 'secondary'">{{ resident.active ? 'Active' : 'Inactive' }}</Badge>
            </div>
            <div class="flex items-center gap-2">
                <Button variant="outline" as-child><Link :href="`/residents/${resident.id}/edit`">Edit</Link></Button>
                <Button variant="destructive" @click="deleteResident">Delete</Button>
            </div>
        </div>

        <div class="grid gap-4 md:grid-cols-2">
            <Card>
                <CardHeader><CardTitle>Contact Info</CardTitle></CardHeader>
                <CardContent class="space-y-2">
                    <div class="flex justify-between"><span class="text-muted-foreground">Email</span><span>{{ resident.email ?? '—' }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Phone</span><span>{{ resident.phone_number }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Country Code</span><span>{{ resident.phone_country_code }}</span></div>
                </CardContent>
            </Card>
            <Card>
                <CardHeader><CardTitle>Personal Info</CardTitle></CardHeader>
                <CardContent class="space-y-2">
                    <div class="flex justify-between"><span class="text-muted-foreground">National ID</span><span>{{ resident.national_id ?? '—' }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Gender</span><span>{{ resident.gender ?? '—' }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Date of Birth</span><span>{{ resident.georgian_birthdate ?? '—' }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Units</span><span>{{ resident.units_count ?? 0 }}</span></div>
                    <div class="flex justify-between"><span class="text-muted-foreground">Leases</span><span>{{ resident.leases_count ?? 0 }}</span></div>
                </CardContent>
            </Card>
        </div>

        <Card v-if="resident.units && resident.units.length > 0">
            <CardHeader><CardTitle>Units</CardTitle></CardHeader>
            <CardContent>
                <div class="space-y-2">
                    <Link v-for="unit in resident.units" :key="unit.id" :href="`/units/${unit.id}`" class="flex items-center justify-between rounded-md border p-3 hover:bg-muted/50">
                        <span class="font-medium">{{ unit.name }}</span>
                        <span class="text-muted-foreground text-sm">{{ unit.community?.name ?? '' }} {{ unit.building?.name ? `/ ${unit.building.name}` : '' }}</span>
                    </Link>
                </div>
            </CardContent>
        </Card>

        <Card v-if="resident.leases && resident.leases.length > 0">
            <CardHeader><CardTitle>Leases</CardTitle></CardHeader>
            <CardContent>
                <div class="space-y-2">
                    <Link v-for="lease in resident.leases" :key="lease.id" :href="`/leases/${lease.id}`" class="flex items-center justify-between rounded-md border p-3 hover:bg-muted/50">
                        <span class="font-medium">{{ lease.contract_number }}</span>
                        <Badge>{{ lease.status?.name ?? '—' }}</Badge>
                    </Link>
                </div>
            </CardContent>
        </Card>

        <Card v-if="resident.dependents && resident.dependents.length > 0">
            <CardHeader><CardTitle>Dependents</CardTitle></CardHeader>
            <CardContent>
                <div class="space-y-2">
                    <div v-for="dep in resident.dependents" :key="dep.id" class="flex items-center justify-between rounded-md border p-3">
                        <span class="font-medium">{{ dep.first_name }} {{ dep.last_name }}</span>
                        <span class="text-muted-foreground text-sm">{{ dep.relationship ?? '—' }}</span>
                    </div>
                </div>
            </CardContent>
        </Card>
    </div>
</template>
